version: '2.0'
services:
    node1:
      container_name: ${PROJECT_NAME}
      image: krkrishna011/apachejmeter-master:v0.2
      volumes:
        - ${Script_Path}:/opt/jmeter/bin/sharedfolder/Script
        - ${Report_Path}:/opt/jmeter/bin/sharedfolder/Report
        - ${Result_Path}:/opt/jmeter/bin/Results
      environment:
        - Extra_params=${Extra_params}
        - Users=${Users}
        - Duration=${Duration}
      command: sh +x ${Script_Path}/script_jmeter.sh
    
    filebeatapts:
      container_name: filebeat-container
      user: root
      build:
        context: filebeat/
        args:
          ELK_VERSION: 7.9.2
      volumes:
        - ${Report_Path}/:/var/log/jmeter/
      command: ["--strict.perms=false"]
      depends_on:
        - node1
        
