version: '2.0'
services:
    node1:
      container_name: ${PROJECT_NAME}
      image: krkrishna011/apachejmeter-master:v0.2
      volumes:
            - /opt/aptsac/jmeter/workspace/${PROJECT_NAME}:/opt/jmeter/bin/sharedfolder/Script
            - /opt/aptsac/jmeter/workspace/report:/opt/jmeter/bin/sharedfolder/Report
            - /opt/aptsac/jmeter/workspace/results:/opt/jmeter/bin/Results
      environment:
            - Extra_params=${Extra_params}
            - Users=${Users}
            - Duration=${Duration}
      #command: tail -f /dev/null 
      #command: opt/jmeter/bin/jmeter-server
      command: sh +x /opt/aptsac/jmeter/workspace/${PROJECT_NAME}/script_jmeter.sh
